<p><img src="https://cdn.1min30.com/wp-content/uploads/2018/03/logo-NBA.jpg" style="width: 295px;"></p>
<p style="text-align: justify;"><span style="font-family: Calibri, sans-serif; font-size: 18px;">&nbsp; &nbsp; &nbsp; Welcome to our team NBA Analytics&nbsp;</span><span style="color: rgb(0, 0, 0); font-family: Calibri, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; float: none; display: inline !important;">project</span><span style="font-family: Calibri, sans-serif; font-size: 18px;">&nbsp; our team is composed of two student in BI engineering <strong>Kevin JUBERT</strong> and <strong>Stanislas EKANDJI KOY</strong>, &nbsp;in this project you&apos;ll find dataset.&nbsp;</span></p>
<p style="text-align: justify;"><span style="font-family: Calibri, sans-serif; font-size: 18px;">The aim of the project is to determine and understand how the data are correlated, for this we have decided to apply a PCA algorithm in Python and &nbsp;the pre processing code.</span></p>
<ul>
    <li style="text-align: justify; font-weight: bold;"><span style="font-family: Calibri, sans-serif; font-size: 18px;"><strong>On this notebook untiltled &quot;Code01PresentationDataset.ipynb&quot; we collect the data into dictionnaries to be easily in another module.</strong></span></li>
    <li style="text-align: justify; font-weight: bold;"><span style="font-family: Calibri, sans-serif; font-size: 18px;"><strong>&quot;Code02DataCleaner.ipynb&quot; notebook file is here to clean the excel file and specialy the &quot;Game&quot; sheet before reduct the dimension via a PCA method</strong></span></li>
    <li style="text-align: justify; font-weight: bold;"><span style="font-family: Calibri, sans-serif; font-size: 18px;"><strong>&quot;Code03PCA.ipynb&quot; is the notebook where we apply the PCA Algorithm</strong></span></li>
</ul>
<p style="text-align: justify;"><br></p>

In [1]:
import pandas as pd

In [2]:
# List all the excel sheet in NBA Data Analytics.xlsx file
xlfile =  pd.ExcelFile("./data/NBA Data Analytics.xlsx")

In [4]:
counter = 1
df = dict() 
for i in xlfile.sheet_names :
    
    if(i !='Games_Details') :
        
        df[i] = pd.read_excel("./data/NBA Data Analytics.xlsx", i)
        print("Feuille {}".format(counter),": \'{}\' ".format(i)," shape of the dataset -> ({})".format(df[i].shape))
        counter+=1

Feuille 1 : 'Teams'   shape of the dataset -> ((30, 10))
Feuille 2 : 'Ranking'   shape of the dataset -> ((102083, 9))
Feuille 3 : 'Games'   shape of the dataset -> ((13744, 17))

In [5]:
df['Games'].head(10)

,GAME_DATE_EST,GAME_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away
0,2021-11-17,22100213,2021,1610612766,97,0.438,0.500,0.313,30,59,1610612764,87,0.367,0.813,0.190,23,48
1,2021-11-17,22100214,2021,1610612765,97,0.425,0.750,0.286,16,42,1610612754,89,0.418,0.737,0.243,14,43
2,2021-11-17,22100215,2021,1610612737,110,0.506,0.833,0.351,28,40,1610612738,99,0.440,0.824,0.268,24,42
3,2021-11-17,22100216,2021,1610612751,109,0.458,0.840,0.375,29,47,1610612739,99,0.393,0.857,0.250,20,50
4,2021-11-17,22100217,2021,1610612748,113,0.483,0.824,0.375,29,39,1610612740,98,0.440,0.786,0.286,18,38
5,2021-11-17,22100218,2021,1610612752,98,0.420,0.667,0.327,25,45,1610612753,104,0.406,0.833,0.289,20,51
6,2021-11-17,22100219,2021,1610612749,109,0.460,0.708,0.324,22,52,1610612747,102,0.417,0.833,0.279,24,48
7,2021-11-17,22100220,2021,1610612750,107,0.500,0.833,0.278,20,35,1610612758,97,0.366,0.760,0.263,19,47
8,2021-11-17,22100221,2021,1610612760,101,0.446,0.563,0.256,18,56,1610612745,89,0.356,0.684,0.286,16,46
9,2021-11-17,22100222,2021,1610612756,105,0.441,0.714,0.333,27,49,1610612742,98,0.413,1.000,0.500,28,50

In [6]:
#df['Games_Details'].head(10)